version: '3'

services:
  app:
    container_name: phonebook
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.29.0
    volumes:
      - './prometheus:/etc/prometheus'
      - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - './grafana/provisioning:/etc/grafana/provisioning'
      - './grafana/phonebook.json:/var/lib/grafana/dashboards/phonebook.json'
      - grafana-storage:/var/lib/grafana
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
  mongodb-interface:
    image: mongo-express
    container_name: mongodb-interface
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  grafana-storage:
  prometheus_data:
