{
 "title": "Phonebook",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_response_time_seconds_sum/http_response_time_seconds_count)"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_responses_status", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Requests total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests", "legendFormat": "{{method}}  {{path}}" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests{job=\"phonebook\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}